spring:
  application:
    name: ${APP_NAME:hms}

  main:
    allow-circular-references: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    enabled: ${MAIL_ENABLED:false}
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

razorpay:
  key-id: ${RAZORPAY_KEY_ID}
  key-secret: ${RAZORPAY_KEY_SECRET}

anthropic:
  api-key: ${ANTHROPIC_API_KEY}
  model: ${ANTHROPIC_API_MODEL}

groq:
  api-key: ${GROK_API_KEY}
  model: llama-3.3-70b-versatile

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID:}
  auth-token: ${TWILIO_AUTH_TOKEN:}
  whatsapp-from: whatsapp:+14155238886   # Twilio's shared sandbox number
  sms-from: +919935232465                # your Twilio trial phone number
  enabled: ${TWILIO_ENABLED:false}        # set to true only when credentials are valid

server:
  port: ${SERVER_PORT:8080}